---
title: "Do Gas Expenditure Shocks Have Different Effects in Recessions & Expansions?"
author: 
- Naafey Sardar
- Lance Bachmeier
output: beamer_presentation
---

# Objective

- How aggregate consumption responds to gasoline expenditures.

- Our observation period is from 1973:Q1-2018:Q2. 

- Using a structural VAR for U.S. data covering 

- Different measures of slack are also used to make sure our results are not dependent on a particular definition of recession.

---

# Introduction

- How aggregate consumption responds to a shock to gasoline expenditures?

- If gasoline consumption is inelastic in the short-run, a positive to gasoline price will 
lead to higher gasoline expenditures, reducing spending on non-gasoline goods and services.

- Kilian & Edelstein (2009, *JME*), Hamilton (2016), Kilian and Baumeister (2016), Herrera et al. (2019),
Gorodnichenko et al. (2019). 

---

# Relationship between Consumption and Gasoline Expenditures

There is a great deal of empirical evidence that a shock to gasoline expenditures
has effects on U.S. Consumption:

- Hamilton (2009, *JPE*)
- Hamilton (1988, *J Econometrics*)
- Farrell and Greig (2015, *JP Morgan Chase*)
- Gicheva et al. (2008, **)

---

# Relationship between Consumption and Oil

In the words of Jannet Yellen (2011):

"A higher price of imported oil is the equivalent of a tax on consumers. It is a transfer from US consumers to foreign oil producers. The effect should be the same as a tax increase. This tends to have a dampening effect on consumer spending."



---

# Fiscal Policy Literature

- Recent research has found that fiscal policy has different effects when the economy is experiencing a recession than it does at other times. 

- Auerbach and Gorodnichenko (2012) found out that fiscal multipliers are larger in recessions as opposed to expansions. 

- If shocks to the gasoline expenditures are equivalent to changes in taxes, and fiscal policy has different effects in recessions and expansions, it follows that the effect of a gasoline expenditure shock should depend on the state of the business cycle.

---

# Implications

- If consistent, then requires a change to empirical and theoretical macroeconomic models that include gasoline prices.

- Failue to find such evidence will be inconsistent with existing literature then exposes a gap in our understanding. 

---

# Data

- We consider the real growth of aggregated and disaggregated consumption.

- Aggregated consumption includes categories like total non-gasoline consumption, durables, nondurables & services PCE.

- Nominal consumption is converted into real consumption using the Price Index for PCE. 

- The recession dates are calculated using Auerbach & Gornodnichenko (2012). 

---

# Data

|   Variables        |     Source    |   Sample Period    |
|:-------------------|:-------------:|:------------------:|
|    Total PCE       |      BEA      | 1973:1-2018:2      |
|    Durables        |      BEA      | 1973:1-2018:2      |
|    Nondurables     |      BEA      |  1973:1-2018:2     |
|    Services        |      BEA      |     1973:1-2018:2  |
|    Motor           |      BEA      |     1973:1-2018:2  |
|    Furnishing      |      BEA      |     1973:1-2018:2  |
|    Other Durables  |      BEA      |     1973:1-2018:2  |
|    Food            |      BEA      |  1973:1-2018:2     |
|    Clothing        |      BEA      |   1973:1-2018:2    |
|  Other Nondurables |      BEA      |     1973:1-2018:2  |
|Housing & Utilities |      BEA      |     1973:1-2018:2  |
|   Transportation   |      BEA      |    1973:1-2018:2   |
|  Food Services     |      BEA      |  1973:1-2018:2     |
|   Other Services   |      BEA      |    1973:1-2018:2   |

---

# Linear Model

We begin the analysis by estimating the effect of a shock to gasoline expenditures
on consumption using the linear VAR model

$$y_{t} = \alpha + \sum_{i=1}^{p} \beta_{i} y_{t-i} + e_{t},$$
where $y_{t} = \left( \Delta exp_{t}, x_t \right)^{\prime}$, $x_{t}$
is a measure of consumption growth in quarter $t$, $exp_{t}$ is the
percentage change in gasoline expenditures in quarter $t$, $e_{t} = \left( e_{exp,t}, e_{x,t} \right)^{\prime}$
is a vector of reduced form residuals, and $\alpha$ and $\beta_{i}$ are
vectors of coefficients.

---

# Identification

- The Cholesky decomposition of variance-covariance matrix of reduced form
residuals suggests that,

$$e_t=
\begin{pmatrix}
e_{exp,t}\\ 
e_{x,t}
\end{pmatrix}=
\begin{bmatrix}
1 & 0\\ 
a_{21} & 1 
\end{bmatrix}
\begin{pmatrix}
\varepsilon_{exp,t}\\ 
\varepsilon_{x,t}
\end{pmatrix}$$

- The ordering is in line with Kilian & Edelstein (2009, *JME*). 

- Different interpretations of the structural shock to gas expenditures. 

---

# Crowding Out of Non-Gasoline Spending

- The bivariate VAR model results suggest that as gas expenditures increase, non-gasoline spending
goes down. 

- This decline in spending is refered to as the 'discretionary income effect'.

- Once consumers are done paying for gas and other gasoline goods, they have less money to spend on other goods and services.

- These results suggest that gas expenditures, do infact play the role of a tax for consumers.

---

# How to Define A Recession

- We follow Auerbach & Goronichenko in constructing recession dates using a transition function,

$$F(z_t)= \frac{exp(-\gamma (z_t-\bar{d}))}{1+exp(-\gamma (z_t-\bar{d}))}, \gamma>0.$$

- Where $z_t$ is equal to the seven quarter moving average growth rate of output and the value of $\gamma$ is calibrated to be equal to 3 so that the economy spends 20% of time in recession i.e. $Pr(F(z_t)>0.8)=0.2$ 

---

# Threshold Model

**Step 1.** Estimate threshold model that is an extension of the Kilian's SVAR model (2009) for each forecast horizon,

$$x_{t}= \alpha+\sum_{i=0}^{k}\phi_{i}I_{t-i}+\sum_{i=0}^{k}\theta_{i}\Delta{y}_{t-i}+\sum_{i=1}^{k}\beta_{i}x_{t-i}$$
$$+\sum_{i=0}^{k}\gamma_{i}\Delta {exp}_{t-i}+\sum_{i=0}^{k}\delta_{i}(I_{t-i} \times \Delta exp_{t-i})+e_{t}$$
where, 

$$I_t=\left\{\begin{matrix}
1 & Recession\\ 
0 & Expansion 
\end{matrix}\right.$$

$$inter_{t-i}=(I_{t-i} \times \Delta exp_{t-i})$$

---

# Methodology

**Step 2.** 
After re-estimating the model, we find the contemporaneous response of $x_t$ to a shock in gasoline expenditures, 

$$x_0^{rec}=\hat{\gamma_0} \Delta exp_0 + \hat{\delta_0} inter_0$$
Similary for an expansion,

$$x_0^{exp}=\hat{\gamma_0} \Delta exp_0$$

This is followed by defining the initial response vectors for each regime,

$$d_{i}^{rec}=\begin{bmatrix}
x_0^{rec} & \Delta{exp_0} & inter_0 
\end{bmatrix}$$

$$d_{i}^{exp}=\begin{bmatrix}
x_0^{exp} & \Delta{exp_0} & 0 
\end{bmatrix}$$

---

# Advantages of Local Projections

- Flexible to accomodate nonlinear specification.

- We do not have to make any assumptions unlike a VAR.

- Local projections has been used by to investigate asymmetric effects of fiscal policy (Auerbach et. al. (2012), Ramey and Zubairy (2018)),
monetary policy (Jorda et. al. (2019)) and oil price shocks (Basher et. al. (2012)).

---

# Methodology

The IRFs for the two states of the economy are given by:

$$\hat{IR}^{rec}_s=\Phi_s {d_i}^{rec}=\hat\beta_s x_0^{rec}+\hat\gamma_s \Delta exp_0+\hat\delta_s inter_0$$ 

and

$$\hat{IR}^{exp}_s=\Phi_s {d_i}^{exp}=\hat\beta_s x_0^{exp}+\hat\gamma_s \Delta exp_0$$ 

where

$${\Phi_s}={\begin{bmatrix}\hat\beta_{i} & \hat\gamma_{i} & \hat\delta_{i}\end{bmatrix}}$$ 

---

# Methodology

Once we construct the impulse responses for both regimes, we can calculate the cumulative impulse response functions. The rationale to use cumulative impulse responses is that it allows us to calculate the deviation of consumption from its' long-run level.

$${CIR_s}^{rec}=\sum_{j=0}^s \hat{IR}^{rec}_j$$

$${CIR_s}^{exp}=\sum_{j=0}^s \hat{IR}^{exp}_j$$

for j=0,...,8

---

# Asymmetric Response

**Step 3.** 
Asymmetric response calculated using the following formula:

$${CIR_s}^{rec}-{CIR_s}^{exp}=\sum_{j=0}^s \hat{IR}^{rec}_j-\sum_{j=0}^s \hat{IR}^{exp}_j$$

$$\Delta{CIR_s}=\sum_{j=0}^s (\hat{IR}^{rec}_j-\hat{IR}^{exp}_j)$$

If $\Delta{CIR_s}<0$, this means that the economy is hit harder by an gasoline expenditure shock in a recession than it would have been in an expansion. $\Delta{CIR_s}>0$ suggest the opposite.

---

# Sensitivity Analysis

- Different measures of recessions have been proposed in the literature.

- We also use an alternative measure of recession derived by Hamilton. 

- Unlike the NBER that relies on its' subjective consideration to identify recessions, he calculates recessions probabilities by applying Bayes' Law.

---

# Conclusion

- We conclude that an increase in gas expenditures acts as a tax on consumers because it crowds out spending on non-gasoline goods.

- We also find evidence of asymmetry in the response of consumption to a shock in gasoline expenditures across recessions and expansions.

- This asymmetry follows Auerbach & Gorodnichenko (2012) in which they argue that fiscal policy has asymmetric effects across the business cycle.

- In the long run, the drop in PCE across a recession is 4 times more than an expansion.  

- Durables and services sector plays a bigger role in explaining the asymmetry.

---


## Questions? {.thank-you-slide}
